[project]
name = "privacytool-api-gateway"
dynamic = ["version"]
description = "API-gateway to handle multiple pseudonymize engines"
requires-python = ">=3.14"
dependencies = [
    "charset-normalizer>=3.4.7",
    "django>=6.0.6",
    "django-cors-headers>=4.9.0",
    "django-environ>=0.13.0",
    "djangorestframework>=3.17.1",
    "fastexcel>=0.20.2",
    "httpx>=0.28.1",
    "polars>=1.42.0",
    "uvicorn[standard]>=0.40.0",
    "whitenoise>=6.12.0",
]

[dependency-groups]
build = [
    "pyinstaller>=6.18.0",
    "setuptools-scm>=9.2.2",
]

dev = [
    "django-stubs>=5.2.9",
    "djangorestframework-stubs>=3.16.8",
    "mypy>=1.19.1",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "pytest-django>=4.11.1",
    "ruff>=0.15.0",
]

[tool.uv]
package = false
required-version = ">=0.10.9"

[tool.setuptools]
packages = []

[tool.setuptools.dynamic]
version = { file = "main/VERSION" }

[tool.ruff]
line-length = 120
exclude = ['migrations']

[tool.ruff.lint]
select = ['ALL']
ignore = [
    'ARG002', # (`request` & `pk` are mandatory for DRF)
    'D106',   # (Meta classes don't need a docstring)
    'DTZ005', # (Timezones are managed by django)
    'SLF001', # (MEIPASS use for PyInstaller)
    'S101',   # (False positives when using with pytest)
    'EXE001', # (Shebang in manage.py is OK without executable bit in Git)
    'COM812', # (May cause conflicts when used with the formatter)
    'PLC0415' # (Lazy load imports)
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.flake8-quotes]
inline-quotes = 'single'

[tool.ruff.format]
quote-style = 'single'

[tool.mypy]
plugins = [
    'mypy_django_plugin.main',
    'mypy_drf_plugin.main',
]

[[tool.mypy.overrides]]
module = 'environ'
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = 'main.settings'

[tool.coverage.run]
data_file = 'pytest/.coverage'

[tool.coverage.html]
directory = 'pytest/html'

[tool.coverage.xml]
output = 'pytest/coverage.xml'

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = 'main.settings'
python_files = ['tests.py', 'test_*.py', '*_tests.py']
cache_dir = 'pytest/.pytest_cache'
addopts = [
    '--cov=.',
    '--cov-report=term:skip-covered',
    '--cov-report=html',
    '--cov-report=xml',
    '--cov-fail-under=25',
    '-p',
    'no:warnings'
]
