# Generated by Django 6.0.7 on 2026-08-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_selection', models.CharField(default='nl', max_length=2)),
                ('engine_selection', models.CharField(blank=True, default='')),
            ],
        ),
    ]
