# Generated by Django 6.1 on 2026-09-14 15:41

import main.storage
import settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_selection', models.CharField(default='nl', max_length=2)),
                ('engine_selection', models.CharField(blank=True, default='')),
                ('reusable_datakey', models.FileField(blank=True, null=True, storage=main.storage.OverwriteStorage(), upload_to=settings.models.datakey_path)),
            ],
        ),
    ]
