# Generated by Django 6.0.7 on 2026-08-28 14:09

import api.models
import main.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeidentificationJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('engine', models.CharField(default=api.models.default_engine)),
                ('input_cols', models.CharField(blank=True)),
                ('input_file', models.FileField(max_length=255, storage=main.storage.OverwriteStorage(), upload_to=api.models.input_path)),
                ('datakey', models.FileField(blank=True, max_length=255, null=True, storage=main.storage.OverwriteStorage(), upload_to=api.models.input_path)),
                ('output_file', models.FileField(blank=True, max_length=255, null=True, upload_to=api.models.output_path)),
                ('output_datakey', models.FileField(blank=True, max_length=255, null=True, upload_to=api.models.output_path)),
                ('data_permission', models.BooleanField(default=False)),
                ('consent_file', models.FileField(blank=True, max_length=255, null=True, upload_to=api.models.output_path)),
                ('log_file', models.FileField(blank=True, max_length=255, null=True, upload_to=api.models.output_path)),
                ('skipped_lines', models.FileField(blank=True, max_length=255, null=True, upload_to=api.models.output_path)),
                ('zip_file', models.FileField(blank=True, max_length=255, null=True, upload_to=api.models.output_path)),
                ('zip_preview', models.JSONField(blank=True, null=True)),
                ('preview', models.JSONField(blank=True, null=True)),
                ('processed_preview', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
        ),
    ]
